config/routes.rb
Rails.application.routes.draw do
  resources :time_trackers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'time_trackers#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/time_tracker.rb
class TimeTracker < ApplicationRecord
    broadcasts_to ->(time_tracker) { :time_trackers }, inserts_by: :prepend, target: 'time_trackers'
    
    before_update :set_ended_at
    def set_ended_at
      self.ended_at = Time.current if status[/stopped/] && ended_at.nil?
    end

    def running?
        status[/running/]
      end
    
    def duration
        if running?
          (Time.current - started_at).to_i
        else
          (ended_at - started_at).to_i
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/time_trackers_controller.rb
class TimeTrackersController < ApplicationController
  before_action :set_time_tracker, only: %i[show edit update destroy]

  # GET /time_trackers or /time_trackers.json
  def index
    start = Time.current
    @time_trackers = TimeTracker.all.reverse

    @time_tracker = TimeTracker.new

    # Rails.logger.debug "The index method took #{Time.current - start}"

    # ::TASKS_LOGGER.debug "We did it! Awesome!"
  end

  # GET /time_trackers/1 or /time_trackers/1.json
  def show; end

  # GET /time_trackers/new
  def new
    @time_tracker = TimeTracker.new
  end

  # GET /time_trackers/1/edit
  def edit; end

  # POST /time_trackers or /time_trackers.json
  def create
    @time_tracker = TimeTracker.new({ started_at: Time.current, status: 'running' }.merge(time_tracker_params))

    respond_to do |format|
      if @time_tracker.save
        format.html { redirect_to @time_tracker, notice: 'Time tracker was successfully created.' }
        format.json { render :show, status: :created, location: @time_tracker }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @time_tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_trackers/1 or /time_trackers/1.json
  def update
    respond_to do |format|
      if @time_tracker.update(time_tracker_params)
        format.html { redirect_to @time_tracker, notice: 'Time tracker was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_tracker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @time_tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_trackers/1 or /time_trackers/1.json
  def destroy
    @time_tracker.destroy
    respond_to do |format|
      format.html { redirect_to time_trackers_url, notice: 'Time tracker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_time_tracker
    @time_tracker = TimeTracker.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def time_tracker_params
    params.require(:time_tracker).permit(:topic, :rate_per_hour, :started_at, :ended_at, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/time_trackers_helper.rb
module TimeTrackersHelper
    def duration_display(time_tracker)
      duration = ActiveSupport::Duration.build(time_tracker.duration).parts

      format('%02d:%02d:%02d', (duration[:hours]||0), (duration[:minutes]||0), (duration[:seconds]||0))
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contractometer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/time_trackers/_form.html.erb
<%= turbo_frame_tag "time_tracker_form" do %>
  <%= form_with(model: time_tracker) do |form| %>
    <div class='row my-2'>
      <div class = 'col-10'>
        <%= form.text_field :topic, class: 'form-control', placeholder: 'What are you working on?' %>
      </div>
      
      <div class = 'col-1'>
        <%= form.text_field :rate_per_hour, class: 'form-control' %>
      </div>
      
      <div class = 'col-1'>
        <%= form.button :button, type: :submit do %>
          <i class="fa-solid fa-play"></i>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/time_trackers/_time_tracker.html.erb
<%= turbo_frame_tag dom_id(time_tracker) do %>
  <div class='row my-2'>
    <div class='col-9'>
      <%= time_tracker.topic %>
    </div>
    <div class='col-1'>
      <%= time_tracker.rate_per_hour %>
    </div>
    <div class='col-1'>
      <% if time_tracker.running? %>
        <div data-controller='timer'
            data-timer-start-value='<%= time_tracker.started_at.to_i * 1000 %>'
            data-timer-refresh-interval-value='1000'
      >
          <%= duration_display time_tracker %>
        </div>
      <%else%>
        <%= duration_display time_tracker %>
      <% end %>
    </div>
    <div class='col-1'>
      <% if time_tracker.running? %>
        <%= form_with(model: time_tracker) do |form| %>
          <%= form.hidden_field :status, value: :stopped %>
          <%= form.button :button, type: :submit do %>
            <i class="text-success fas fa-stop"></i>
          <% end %>
        <% end %>
      <%else%>
        <i class="text-danger fas fa-stop"></i>
      <% end %>
    </div>
  </div>
<% end %>

app/views/time_trackers/edit.html.erb
<h1>Editing Time Tracker</h1>


<%= link_to 'Show', @time_tracker %> |
<%= link_to 'Back', time_trackers_path %>

app/views/time_trackers/index.html.erb
<%= turbo_stream_from :time_trackers %>

<%= render 'form', time_tracker: @time_tracker %>
<hr>

<%= turbo_frame_tag :time_trackers do %>
  <%= render @time_trackers %>
<% end %>

app/views/time_trackers/new.html.erb
<h1>New Time Tracker</h1>

<%= render 'form', time_tracker: @time_tracker %>

<%= link_to 'Back', time_trackers_path %>

app/views/time_trackers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Topic:</strong>
  <%= @time_tracker.topic %>
</p>

<p>
  <strong>Rate per hour:</strong>
  <%= @time_tracker.rate_per_hour %>
</p>

<p>
  <strong>Started at:</strong>
  <%= @time_tracker.started_at %>
</p>

<p>
  <strong>Ended at:</strong>
  <%= @time_tracker.ended_at %>
</p>

<p>
  <strong>Status:</strong>
  <%= @time_tracker.status %>
</p>

<%= link_to 'Edit', edit_time_tracker_path(@time_tracker) %> |
<%= link_to 'Back', time_trackers_path %>